version: '2'
services:
  server:
    build: ./server/build
    image: pamtrak06/registry-server
    ports:
      - "5000:5000"

  web:
    build: ./web/build
    image: pamtrak06/registry-frontend
    environment:
      - "REGISTRY_URL=http://registry_1:5000/v2"
      - "REGISTRY_NAME=localhost:5000"
    ports:
      - "8082:8080"
    volumes:
      - $PWD/web/volumes/config.yml:/conf/config.yml:ro
    links:
      - registry_1

