version: '2'
services:
  registry-server:
    build: ./registry-server/build
    image: pamtrak06/registry-server
    ports:
      - "5000:5000"

  registry-web:
    build: ./registry-web/build
    image: pamtrak06/registry-web
    environment:
      - "REGISTRY_URL=http://registry-server_1:5000/v2"
      - "REGISTRY_NAME=localhost:5000"
    ports:
      - "808O:8080"
    volumes:
      - $PWD/registry-web/volumes/config.yml:/conf/config.yml:ro
    links:
      - registry-server

